dataset_name: OpenSound/CapSpeech-RealSets
max_words: 100
librittsr_dir: /export/corpora7/CapSpeech-real/LibriTTS_R_hubert_features
other_dir: /export/corpora7/CapSpeech-real/hubert_features

# size of vit model; base or large
input_dim: 1024
hidden_dim: 512
kernel_size: 5
padding: 2
pooling: 5
dropout: 0.4
audio_width: 768

batch_size: 128

queue_size: 57600 # set to max_epoch * 10
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 3e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 3000
